### ISSUE TITLE
C++ support

### ISSUE THREAD

**Issue by Trass3r** [CyberShadow/DustMite#14]
Do you have some tips for creating a C++ parser for DustMite?
I could really use a usable reduction tool for a clang ICE.

**Comment by Trass3r** [comment]
Maybe a cpp switch could be created as a shortcut for the nicely working `--split *.{c,cpp,cxx,h,hpp}:d`?

**Comment by CyberShadow** [comment]
I don't think so, since we're not really parsing C++.
