### ISSUE TITLE
Fuzzer

### ISSUE THREAD

**Issue by CyberShadow** [CyberShadow/DustMite#23]
DustMite's splitter should allow nice fuzzing, e.g. by replacing a random node with another random node from elsewhere in the code.

**Comment by wilzbach** [comment]
I just tried to dustmite an ICE in Phobos ... and accidentally only specified the file of the ICE -> ended up with a totally different ICE.

So I believe if DustMite is turned to mutate Phobos's code to search for ICEs, it would yield lots of them.
(doesn't have to Phobos, will probably work with any of the bigger libraries).

**Comment by CyberShadow** [comment]
Added `--fuzz` in d4303cac4145601e2e5923c51c0493c4774ee87f, with one type of transformation (swap random nodes). Haven't tried it with DMD yet.
