### ISSUE TITLE
DustMite should attempt to autodetect error patterns

### ISSUE THREAD

**Issue by MartinNowak** [CyberShadow/DustMite#27]
It's often a little difficult to write the correct matcher for an error and it would be nice if dustmite automatically recognized the most common errors.

https://github.com/CyberShadow/DustMite/wiki/Useful-test-scripts

So for example if I run `dustmite src dmd foo.d` and get an assertion in dmd then dustmite should reduce matching a segfault of dmd and grepping for the assertion.
Likewise a compiler segfault without output should be matched as such.
And for crashing applications (dustmite src rdmd foo) it should attempt to extract the function where an error occurred.

**Comment by CyberShadow** [comment]
I really don't see a way to reliably implement this in a sensible way.

I agree that this could be done for ICEs, though ICEs are only a small part of reduced bugs.

Automatically creating a test script for a segfault is very difficult. Simply reducing for a segfault will very quickly result in a very small program that dereferences a null pointer.

I don't even know how I would go about "extract the function where an error occurred". Parsing stack traces?

Essentially, aside from the ICE case, this is asking for magic :)

**Comment by CyberShadow** [comment]
Closing since as it is, this is too vague. This needs some concrete goals / examples and proposed plans for reaching said goals.
