### ISSUE TITLE
Update dustmite in tools repo

### ISSUE THREAD

**Issue by MartinNowak** [CyberShadow/DustMite#29]
For the upcoming 2.067 release it would be nice to also update dustmite, because I just hit a bug (ignored SIGINT) that is already fixed here ;).

**Comment by CyberShadow** [comment]
> because I just hit a bug (ignored SIGINT) that is already fixed here

I don't remember fixing this?

**Comment by CyberShadow** [comment]
https://github.com/D-Programming-Language/tools/pull/162

**Comment by MartinNowak** [comment]
> I don't remember fixing this?

Well in the version that shipped with 2.066.1 SIGINT is sent to the child process and not dustmite itself, meaning you can't use Ctrl+C to stop a run.
Maybe you're using a different std.process function by now?

**Comment by CyberShadow** [comment]
I don't think so. Maybe something changed in Phobos?

**Comment by MartinNowak** [comment]
> I don't think so. Maybe something changed in Phobos?

Not sure, but you're right, the dustmite from 2.067.0-b2 also works.
And I can't reproduce the error with any version of dustmite/dmd, even when checking out v2.066.1.
Would be nice to include a `git describe` slug in some `dustmite --version` command.
