### ISSUE TITLE
--obfuscate should obfuscate AFTER reduction (as an option)

### ISSUE THREAD

**Issue by timotheecour** [CyberShadow/DustMite#33]
it would be nice to option to combine --obfuscate and reduction to make reductions more unique across problems.
Obfuscate would be run on the reduced output only (for speed), and would be deterministic, so different people running into same compiler bug from their own different programs would be more likely to end up with word-for-word identical reductions, make it especially useful to find your bug in bugzilla.
This could even be a default.

Furthermore, it would be nice if dustmite attempted to reduct strings to "" (again for generating as identical as possible outputs)

**Comment by CyberShadow** [comment]
Um.

1. If you want to reduce and then obfuscate, you can write a batch file to do that. A full reduction is usually a several step process involving human assistance. I don't see the point in making reduction part of obfuscation.

2. Unless you use the `--keeplength` switch, reductions are already deterministic.

I'll look into splitting up strings.

**Comment by timotheecour** [comment]
Maybe I didn't explain my motivation properly:
the point of using obfuscation here was to generate outputs that are more likely to be identical for a class of compiler bug regardless of the details of the input file such as variable/function names:

right now when i reduce a bug i get:
void runInference(int num_steps){ badcode("/tmp/"); };
but another person may get a different output module variable renaming and other factors (ordering etc).

With obfuscation, there's some chance everyone would end up with the same output:
void A(int B){ badcode(""); };

I know it's a small thing, but it does make bug sorting/merging easier.

**Comment by CyberShadow** [comment]
Honestly, I think that it's exceedingly unlikely to get the same reduction result from different codebases even with obfuscation. Almost always there are too many ways to write the same code, as far as syntax and semantics are concerned.

**Comment by CyberShadow** [comment]
> bug sorting/merging

A somewhat related project of mine I haven't really announced anywhere:
https://github.com/CyberShadow/DBugTests

**Comment by CyberShadow** [comment]
> Unless you use the --keeplength switch, obfuscations are already deterministic.

Erm, they're deterministic in all cases - I use a RNG with a default seed for `--keeplength`.

**Comment by timotheecour** [comment]
>> A somewhat related project of mine I haven't really announced anywhere:

That's really cool. I wonder why you haven't announced it yet.
Automation is really the way to go indeed. 

I still think maximal reductions are likely to create identical outputs automatically in a number of cases, with each of those heuristics being attempted:

* reformatting
* renaming via obfuscate
* removing comments
* reducing strings to ""
* removing ith argument to a function (is that easy across modules? within a module?)
* harder: pulling in automatically import dependencies into the working set so they can be reduced too (eg std.range etc). That could be doable since dmd spits -v out the file for each module

**Comment by CyberShadow** [comment]
> That's really cool. I wonder why you haven't announced it yet.

Mainly because I don't really expect that anyone is going to use it, or help me improve it.

> I still think maximal reductions are likely to create identical outputs automatically in a number of cases, with each of those heuristics being attempted:

I think this is a task for a separate project. But I've reduced a lot of test cases, and I'm skeptical of the idea. In many cases reductions that you may think are minimal really aren't, but you need insight in compiler internals to reduce further (because at some point you need to add or replace code in order to remove other code).

**Comment by CyberShadow** [comment]
> I'll look into splitting up strings.

Dustmite currently treats strings as a single token. Since reducing a string to an empty one is very unlikely to allow a reduction to occur elsewhere, I think there is little value in refactoring DustMite to allow this type of reduction, so it would have to be done by the above-mentioned separate project.
