### ISSUE TITLE
reduction should attempt to remove function parameters

### ISSUE THREAD

**Issue by timotheecour** [CyberShadow/DustMite#34]
Many times dustmite stops making progress because a certain function takes arguments that prevents further reductions.

How about attempting to remove ith parameter to a function declared in the working set, and adjusting the callers as needed.

**Comment by CyberShadow** [comment]
DustMite has purposefully very limited knowledge about the syntax of D (and nothing at all about semantics). Teaching DustMite more about D syntax will result in shrinking the set of bugs DustMite is able to reduce (e.g. DustMite might be unable to reduce a program it cannot parse).

So... "adjusting the callers as needed" is way outside DustMite's scope. Attempting to add default parameters to things that look like a function declaration might be more feasible, but this goes against DustMite's core principle that it only ever removes code (and these default parameters will likely be removed the next time DustMite goes over them).

**Comment by CyberShadow** [comment]
Initial work based on a crude heuristic:
https://github.com/CyberShadow/DustMite/commit/c671d728fca468f2a19c9498e8096ff3e94521ce

**Comment by CyberShadow** [comment]
OK, after some tweaking I'm reasonably happy with it.

**Comment by timotheecour** [comment]
awesome!
