### ISSUE TITLE
better progress indicator: also show number of tokens at each iteration

### ISSUE THREAD

**Issue by timotheecour** [CyberShadow/DustMite#35]
eg instead of:
[ 95.5%] Remove [00001110010001001] => Yes
show:
[ 95.5%] Remove [00001110010001001] => Yes tokens:117
That's a good easy to read indicator of progress

**Comment by CyberShadow** [comment]
I don't really see how this is a considerable improvement...

The placement in your example is inconsistent (the new data is printed after a test run).
