### ISSUE TITLE
multicore option

### ISSUE THREAD

**Issue by magicl** [CyberShadow/DustMite#38]
Is it possible to make dustmite use multi-core when available? For some projects, a lot of time ends up being spent on only a single core (link, test execution), and it seems like one could get a significant speedup if we added a parameter to specify number of concurrent processes to run.

It seems like a lot of time is spent trying out modifications that don't result in the desired output, and is then discarded. Modification attempts like this could be run in N threads, with a join after each iteration, where you could see which were successful, and then start all threads again from the new starting-point..

Doable?

**Comment by CyberShadow** [comment]
Yes, but it requires refactoring half the code. The strategy algorithms need to be rewritten from an imperative style into a state machine, because they must have copyable/rewindable state.

**Comment by John-Colvin** [comment]
Just wanted to say that it would be amazing if this worked. I often have to wait for hours for dustmite runs with so many cores sitting idle.

**Comment by CyberShadow** [comment]
Implemented

**Comment by CyberShadow** [comment]
Should work much better as of bf407bc40dae5d7b57b5c2511f651e8eb7e66566 and f85acdfae6c5e6fd81af87d964114b8e43356f11.
