### ISSUE TITLE
module merging

### ISSUE THREAD

**Issue by John-Colvin** [CyberShadow/DustMite#39]
I often end up with code like this after reduction:

```D
// a.d
void foo();

// b.d
import a;
void bar() { foo(); }
```

where if I manually merge the two files and remove the import, the test still passes. Is there some way dustmite could perform this reduction? It can make a huge difference in big projects

**Comment by CyberShadow** [comment]
It already does, see:
https://github.com/CyberShadow/DustMite/tree/master/tests/merge

**Comment by John-Colvin** [comment]
Hmm, OK, I'll close this for now and re-open if I can find a concrete example.
