### ISSUE TITLE
Removing unused imports

### ISSUE THREAD

**Issue by cym13** [CyberShadow/DustMite#40]
_Improvement proposal_

Right now is seems that the only way to know which imports are unused is to try manually to remove them. I think making it a known feature by only trying to change import lines could be a valuable improvement.

**Comment by CyberShadow** [comment]
DustMite already does this?

https://github.com/CyberShadow/DustMite/tree/master/tests/imports

**Comment by CyberShadow** [comment]
Oh, never mind. I understand what you mean now.

**Comment by CyberShadow** [comment]
Maybe once the new import fixes are in place. Currently such a pass will remove a lot of imports that are "used", but the program will still compile despite the imports being removed, due to broken DMD import logic (issues 313 and 314).

**Comment by CyberShadow** [comment]
BTW, DFix (or some other DScanner-based tool) could also be in a position to solve this, but using a more structured approach.

**Comment by CyberShadow** [comment]
Added a `--remove` switch in ca18a072b919a477ad208de0c15251ed938f00e5.

You can use it to reduce only import declarations with: `--remove '\s*\b(?:static\s+)?import [^;]*;\s*'`

The test case in that commit does this.
