### ISSUE TITLE
A new switch `--strip-unittests`

### ISSUE THREAD

**Issue by 9rnsr** [CyberShadow/DustMite#41]
_This is an enhancement request._

Before the start of dustmite, if we already know the unittest blocks not affect to the test script result, dustmite can strip off `unittest` blocks and `version(unittest)` declarations in preparation, similar to `--strip-comments` switch.

Pros: It can speed up dustmiting process in specific case.

When I tried to use dustmite a failure of minimal script with Phboos code, although the script compilation had not required -unittest switch, it had consume much times to remove unused unittest blocks. I think that usually big projects contain many unittest blocks, so the proposed feature would become useful in many cases.

**Comment by CyberShadow** [comment]
I am really skeptical that such a switch would really have a significant effect on the total reduction time. Removing a unittest block should happen in one test, or even less if multiple unit tests are grouped together.

Can you provide a fully self-contained example where you think such a switch would help?

**Comment by JohanEngelen** [comment]
I also think this will speed up dustmiting Phobos. Just now I am dustmiting phobos because of a compiler bug. Phobos's unittests often depend on functions of other packages. Such a unittest block will prevent stripping of function in another package, until finally after many steps the unittest block is removed.

I can give you an example where dustmiting phobos is necessary to reduce an LDC bug, if that helps.

**Comment by JohanEngelen** [comment]
@CyberShadow Will this be hard to add? If not, I'm going to try and implement it, as I think it will speed up my dustmiting a ton.

**Comment by CyberShadow** [comment]
> Will this be hard to add?

Not really.

> I think it will speed up my dustmiting a ton.

`unittest` blocks make up about 0.1% of total nodes in Phobos source code, so I'm really skeptical of that.

**Comment by JohanEngelen** [comment]
Yeah, I thought they need to compile, but I guess they only need to parse.

**Comment by CyberShadow** [comment]
> Can you provide a fully self-contained example where you think such a switch would help?

Let's reopen if/when someone finds one.
