### ISSUE TITLE
Ignore .DS_Store file on OS X

### ISSUE THREAD

**Issue by JohanEngelen** [CyberShadow/DustMite#42]
Mac's Finder (file browser) automatically adds .DS_Store files to browsed folders. So there may be a .DS_Store file in the folder that dustmite is going to run on. dustmite then errors with:
```
Suspicious file found: crash2/.DS_Store
You should use a clean copy of the source tree.
If it was your intention to include this file in the file-set to be reduced,
re-run dustmite with the --force option.
```

Perhaps dustmite could just ignore `.DS_Store`, or files starting with `.` in general?

**Comment by JohanEngelen** [comment]
I guess I could work around this by specifying `--reduce-only MASK`.  I myself find it a little annoying to always have to specify --reduce-only though...

**Comment by JohanEngelen** [comment]
How about a short option to ignore unusual files? --force will include them, how about an option --ignore-unusual, with a one-char shorthand alternative name?

**Comment by CyberShadow** [comment]
You could also run `find -name .DS_Store -delete` before running DustMite.

In practice, using `--force` will not affect speed by a lot, unless the file is very large.

**Comment by JohanEngelen** [comment]
Having to do an extra command is pretty annoying imho. 
But I'll settle for just doing --force always.
