### ISSUE TITLE
Assert expressions shouldn't be reduced

### ISSUE THREAD

**Issue by nordlow** [CyberShadow/DustMite#48]
Dustmite incorrectly reduces assert expressions in code such as

```D
module faulty;

auto identity(T)(T x)
{
    return x;
}

auto square(T)(T x)
{
    const y = identity(x);
    if (x == 4)
    {
        return y*y - 1;         // bug
    }
    else
    {
        return y*y;
    }
}

@safe pure nothrow unittest
{
    assert(square(2) == 4);     // ok
    assert(square(3) == 9);     // ok
    assert(square(4) == 16, "Some specific failure in " ~ square.stringof); // triggers bug
}
```

into something like

```D
auto square(T)(T x)
{
}

unittest
{
    assert(4 == 16, "Some specific failure in " ~ square.stringof); // triggers bug
}
```

when called to grep for failure string

```
Some specific failure in square(T)(T x)
```

Is this easy to fix?

**Comment by CyberShadow** [comment]
> Dustmite incorrectly reduces assert expressions in code such as

DustMite is working correctly, *you* are using it incorrectly :)

> Is this easy to fix?

You can fix your usage of DustMite by using NoRemove blocks, `--noremove`, or by moving the test code outside the code that is to be reduced.

See the wiki for more information:
https://github.com/CyberShadow/DustMite/wiki#selective-minimization
