### ISSUE TITLE
Please remove or replace non-free files

### ISSUE THREAD

**Issue by ximion** [CyberShadow/DustMite#50]
Hi!
The inclusion of non-free code pieces currently prevents Debian and other distributions from including Dustmite into their repositories.
The problematic files are https://github.com/CyberShadow/DustMite/blob/master/tests/lines/src.dump and https://github.com/CyberShadow/DustMite/blob/master/tests/lines/src/alice30.txt

```
[3]  Pay a trademark license fee to the Project of 20% of the
     net profits you derive calculated using the method you
     already use to calculate your applicable taxes.  If you
     don't derive profits, no royalty is due.  Royalties are
     payable to "Project Gutenberg Association / Illinois
     Benedictine College" within the 60 days following each
     date you prepare (or were legally required to prepare)
your annual (or equivalent periodic) tax return.
```

Since this imposes restrictions on how the software is used and prevents us from bundling it with Debian (as then people can not sell copies of Debian anymore), we currently can not include Dustmite (or need to remove the problematic files).

See https://www.debian.org/social_contract#guidelines for what makes free software free.

It would be awesome if you could replace the text with a different one under a completely free license.
Thanks!

**Comment by CyberShadow** [comment]
Hi,

These files are not part of the program's source code, only the test suite.

Distribution of DustMite should not include anything under the tests directory.

Thanks.

**Comment by CyberShadow** [comment]
That said, replacing these files shouldn't be an issue.

It's worth noting that this file is taken from the DMD test suite, which is also shared to some extent with GDC and LDC.

**Comment by ximion** [comment]
Nice, thank you!
WE have both GDC and LDC in Debian, so this is indeed something that needs to be looked into... - Thanks for the hint!

**Comment by ximion** [comment]
https://packages.debian.org/sid/dustmite :-)
The software fails to build from source using GDC on x86: https://buildd.debian.org/status/fetch.php?pkg=dustmite&arch=i386&ver=0%7E20170126.e95dff8-1&stamp=1485508123&raw=0

I assume this is a GDC bug, but I'll need to take a closer look at it first.

**Comment by CyberShadow** [comment]
> https://packages.debian.org/sid/dustmite :-)

Nice!

> The software fails to build from source using GDC on x86: https://buildd.debian.org/status/fetch.php?pkg=dustmite&arch=i386&ver=0%7E20170126.e95dff8-1&stamp=1485508123&raw=0
> 
> I assume this is a GDC bug, but I'll need to take a closer look at it first.

That might simply be because of how old GDC's frontend is.

I'll see if a simple workaround is possible from DustMite's side.

**Comment by ximion** [comment]
Otherwise I might just compile it with LDC - GDC has the advantage that it is tied into GCC and is well-maintained by our toolchain maintainers and ported to many architectures - and having Dustmite available on more architectures is definitely useful.

**Comment by CyberShadow** [comment]
> The issue only appears on x86, amd64, x32 etc. are fine - I can't see anything arch-specific in that code, so I think the compiler is doing something wrong there.

Yeah... I can't reproduce it with `-m32` either (with gdc-6.2.1-1 on Arch). No idea what might be wrong.
