### ISSUE TITLE
Stable branch?

### ISSUE THREAD

**Issue by Temtaime** [CyberShadow/DustMite#57]
Hello.
Seems there's only master branch, but this tool is widely used.
Maybe there's a reason to create a stable branch, even if it will not differ from master most of the time?

**Comment by CyberShadow** [comment]
The stable version is located at https://github.com/dlang/tools/tree/master/DustMite.
That is the version that is distributed with DMD.

Changes in this repository are periodically copied there.

Thank you for your consideration.

**Comment by Temtaime** [comment]
Thanks for a link.
Got it.
