### ISSUE TITLE
DustMiteNoRemoveStart/Stop ignored

### ISSUE THREAD

**Issue by berni44** [CyberShadow/DustMite#60]
I noticed, that dustmite sometimes removes code, which is marked not to be removed. Small testcase:

`test.d`:

```
import sub.sub;

// DustMiteNoRemoveStart
unittest
{
}
// DustMiteNoRemoveStop
```

And in `sub/sub.d`:

```
module sub.sub;

```

called with `dustmite  . "dmd -main -unittest -run test.d sub/sub.d"`

I tried this with several versions (*) of dustmite, including the latest (selfcompiled, linux). According to the dump the correct Entieties are marked as "noRemove", but are removed anyway.

(*) By the way `dustmite --version` doesn't work, nor does `dustmite -V` (a Phobos bug?).

**Comment by CyberShadow** [comment]
> According to the dump the correct Entieties are marked as "noRemove", but are removed anyway.

Yes, it was an omission in the logic of the "Concat" reduction type.

> called with `dustmite . "dmd -main -unittest -run test.d sub/sub.d"`

Note that in this command line, `sub/sub.d` is passed as a runtime argument to the built/executed program (`test.d`), and thus is ignored.

> (*) By the way `dustmite --version` doesn't work, nor does `dustmite -V` (a Phobos bug?).

It was added relatively recently, so the versions you tried it with may not have had it yet.

**Comment by berni44** [comment]
> > called with `dustmite . "dmd -main -unittest -run test.d sub/sub.d"`
> 
> Note that in this command line, `sub/sub.d` is passed as a runtime argument to the built/executed program (`test.d`), and thus is ignored.

Oh, thanks. I've been using rdmd for long and just recently changed to calling dmd directly. I still need to get used to this.

> > (*) By the way `dustmite --version` doesn't work, nor does `dustmite -V` (a Phobos bug?).
> 
> It was added relatively recently, so the versions you tried it with may not have had it yet.

Indeed. With the latest version it worked.

Thank you! :-)
