### ISSUE TITLE
Protected unittest moved to different file

### ISSUE THREAD

**Issue by berni44** [CyberShadow/DustMite#61]
The fix of issue #60 seems to have caused a regression (or showed up another bug):

`test.d`:

```
import sub.sub;

auto pp(int a, int b)
{
    return a^^b;
}

// DustMiteNoRemoveStart
unittest
{
    assert(pp(3,4) == 81);
}
// DustMiteNoRemoveStop
```

And in `sub/sub.d`:

```
module sub.sub;

```

called with `dustmite . "dmd -unittest -main -i -run test.d`.

This time, the unittest is moved to `sub/sub.d`, while `test.d` is empty.

**Comment by CyberShadow** [comment]
Currently this is by design. The code was moved, not removed. Is it a problem?

**Comment by berni44** [comment]
> Currently this is by design. The code was moved, not removed. Is it a problem?

Yes, I think so. After the code was moved to `sub.d`, it is not executed anymore and thus `pp` could be removed although it is essential. Also, `sub.d` does not know about `pp`.

What I plan to do with it, is to reduce whole Phobos, but to keep all unittests. This will probably result in something similar like a coverge analysis, but I hope for deeper insights, when lines are only partially removed.
