### ISSUE TITLE
Issue with dmd  color output

### ISSUE THREAD

**Issue by andre2007** [CyberShadow/DustMite#63]
Depending whether color output is on or off in dmd (default is on), there is different text output. E.g.
``` d
void main()
{
    int i;
    e = 3;
}
```

Color on:
```
sample.d(4): Error: undefined identifier e
```

Color off:
```
sample.d(4): Error: undefined identifier `e`
```

Therefore if you copy the text (from colored output) in the clipboard and then search via dustmite, you will not get any result. I always fall into this trap. You may add this info to your wiki.

(I also created a dmd ticket, to solve this issue, but it was closed as won't fix: https://issues.dlang.org/show_bug.cgi?id=20788)

**Comment by CyberShadow** [comment]
Topics which do not describe a defect in the software hosted by the issue tracker's repository are not really appropriate to be posted in the issue tracker.

> You may add this info to your wiki.

The wiki is open to contributions from anyone with a GitHub account.
