### ISSUE TITLE
Source Reductions Prio List

### ISSUE THREAD

**Issue by nordlow** [CyberShadow/DustMite#64]
I'm missing a way to hint dustmite about files it should start reducing first to quickly reduce the time it takes to run the command to be reduced.

**Comment by CyberShadow** [comment]
It's not built in, because you can achieve this by running `dustmite --reduce-only 'priority-files/*' src tester && dustmite src.reduced tester`.

**Comment by CyberShadow** [comment]
I would also suggest trying `--strategy careful` in situations where a priority list might conceivably be faster. I will probably make it the default soon.

**Comment by nordlow** [comment]
> It's not built in, because you can achieve this by running `dustmite --reduce-only 'priority-files/*' src tester && dustmite src.reduced tester`.

Ahh, I missed that. Thanks!

**Comment by nordlow** [comment]
> I would also suggest trying `--strategy careful` in situations where a priority list might conceivably be faster. I will probably make it the default soon.

This is not convenient I still want to reduce potentially all files. Afaict this is not a prio-list it's an inclusion list.

**Comment by nordlow** [comment]
> It's not built in, because you can achieve this by running `dustmite --reduce-only 'priority-files/*' src tester && dustmite src.reduced tester`.

This is not convenient I still want to reduce potentially all files. Afaict this is not a prio-list it's an inclusion list.

**Comment by CyberShadow** [comment]
The first command reduces only the priority files. The second command continues from the first command's result and reduces all files. I understand that this is your goal, is it not?

**Comment by nordlow** [comment]
> The first command reduces only the priority files. The second command continues from the first command's result and reduces all files. I understand that this is your goal, is it not?

Ahh. I see. Yes. Thanks. Would still be useful to have a flag for setting files to try reducing first, though.

**Comment by CyberShadow** [comment]
I think it would be more useful to maximize composability. For instance, what if you want to have multiple levels of priority, or would like to insert some other kinds of rules or transformations in-between those levels?

**Comment by nordlow** [comment]
Ok, cool.

**Comment by CyberShadow** [comment]
> I would also suggest trying `--strategy careful` in situations where a priority list might conceivably be faster. I will probably make it the default soon.

After some testing I would no longer recommend the `careful` strategy.

For reducing builds which use globbing (e.g. like Dub) as opposed to recursive compilation  (e.g. like rdmd), the `lookback` strategy may be faster than the default strategy.

**Comment by nordlow** [comment]
> > I would also suggest trying `--strategy careful` in situations where a priority list might conceivably be faster. I will probably make it the default soon.
> 
> After some testing I would no longer recommend the `careful` strategy.
> 
> For reducing builds which use globbing (e.g. like Dub) as opposed to recursive compilation (e.g. like rdmd), the `lookback` strategy may be faster than the default strategy.

What do you mean by globbing in this context?

**Comment by CyberShadow** [comment]
Dub finds all `*.d` files and passes them to the compiler, whether any other code uses that module or not. This is in contrast to `rdmd` or `dmd -i`, which only causes the compiler to look at a `.d` file if it's actually imported.
