### ISSUE TITLE
Generate and Use Coverage at each run

### ISSUE THREAD

**Issue by nordlow** [CyberShadow/DustMite#65]
There is already

```
  --coverage DIR     Load .lst files corresponding to source files from DIR
```

. Why doesn't `dub dustmite` generate new coverage information "at each call" to `dub run` and use that via `loadCoverage` when deciding which code to remove prior to subsequent call?!!! Wouldn't this enable amazingly faster reduction speed for D especially in the reduction of dependencies.

I guess most of this logic should be implemented in `dub`.

Ping, @CyberShadow.

See https://github.com/CyberShadow/DustMite/blob/master/dustmite.d#L2405

**Comment by CyberShadow** [comment]
What are you trying to achieve with `--coverage`?

Can you describe your use case in more detail?

**Comment by nordlow** [comment]
I thought `loadCoverage()` gave hints to the reduction algorithm. Maybe I was wrong....

**Comment by CyberShadow** [comment]
`--coverage` makes DustMite avoid reducing code that ran. Generally that set of code shouldn't change. It's possible that it does change, e.g. if DustMite reduces some non-code declarations that cause some code to no longer run, but I can't think of a practical use case for this scenario.

**Comment by CyberShadow** [comment]
> the algorithm could start with remove the single lines that aren't covered typically inside conditionals and then try removing functions that were called in covered lines... Are you following?

In many cases it's just as useful to try reducing code that ran as everything else, so I can't really think of a good argument in favor of that.

**Comment by nordlow** [comment]
Btw, my dustmite reduction takes too long time reducing packages. What strategy should I try then?

**Comment by nordlow** [comment]
Btw, my dustmite reduction takes too long time reducing packages. What strategy should I try then?

**Comment by CyberShadow** [comment]
Have you tried `--strategy=careful` yet?

**Comment by nordlow** [comment]
Now. I'll try that. Can I abort a dustmite and then use the the result as input to a new dustmite?

**Comment by CyberShadow** [comment]
Of course (assuming you didn't use `--no-save`).

**Comment by nordlow** [comment]
I first needed https://github.com/dlang/dub/pull/2173.

**Comment by nordlow** [comment]
Btw, at https://dlang.org/blog/2020/04/13/dustmite-the-general-purpose-data-reduction-tool/ what do you mean by

"The parser DustMite uses for D source code is intentionally very simple because it needs to handle potentially invalid D code, and you don’t want your bug reduction tool to also crash on top of the compiler."

? If the compilation always passes after every reduction why does parser need to handle invalid D code? What do you mean by invalid code?

**Comment by nordlow** [comment]
Btw, is there a node deletion history logged on disk somewhere?

**Comment by CyberShadow** [comment]
> Btw, does dustmite utilize all the cores when checking if a set of tried splits succeeds in create a program the compiles?

I didn't understand that beyond "all cores".

You can ask DustMite to use all cores by using the `-j` flag.

No idea about the Dub side.

**Comment by CyberShadow** [comment]
> ? If the compilation always passes after every reduction why does parser need to handle invalid D code?

It doesn't know that. You might be reducing a bug where compilation fails due to the bug you're trying to create a test case for.

**Comment by CyberShadow** [comment]
> Btw, is there a node deletion history written to disk during the call to DustMite?

There is `--trace` which will save verbose snapshots of every reduction attempt and whether it succeeded.
