### ISSUE TITLE
Reduce File Copying

### ISSUE THREAD

**Issue by nordlow** [CyberShadow/DustMite#67]
Could the copying of the root directory tree be avoided by making use of symbolic links for copies of directories and hardlinks for copies of files into the original source tree. For files that aren't reduced that aren't modified that is.

See also https://superuser.com/a/1575148.

**Comment by CyberShadow** [comment]
DustMite doesn't know which files will be modified.

However, you can do this yourself, by placing them outside of the tree.

You may also find `--temp-dir` useful.

**Comment by nordlow** [comment]
> DustMite doesn't know which files will be modified.

What do you mean. I thought the dustmite process is the only one that is supposed to modify the sources and and data. Why not have such modified file be copied on demand when it's modified by DustMite?

> However, you can do this yourself, by placing them outside of the tree.

Which tree are you referring to? The xxx.reduce.1 tree?
And what is "placing them" referring to?

**Comment by CyberShadow** [comment]
> What do you mean? I thought the dustmite process is the only one that is supposed to modify the sources and and data.

No, the test command is allowed to make any modifications it needs to its copy of the source files.

> Which tree are you referring to? The xxx.reduce.1 tree?

The input directory, the one you specify on the command line.

>  And what is "placing them" referring to? All the input files?

Only put the files you want to reduce in the source directory. If you need to use any other files in your test command, you can copy (or symlink, or hardlink) them in before doing anything else.

**Comment by nordlow** [comment]
> > What do you mean? I thought the dustmite process is the only one that is supposed to modify the sources and and data.
> 
> No, the test command is allowed to make any modifications it needs to its copy of the source files.

I believe that is an unfortunate assumption. Most/all build systems are by convention not allowed to make modifications to the sources (registered by the underlying VCS).

**Comment by CyberShadow** [comment]
> I believe that is an unfortunate assumption.

I doubt it, all breadth-first strategies are likely make some modifications to all inputs quickly.

> Could we have this behavior be controlled behind a flag?

No, I don't see the point. Furthermore, if the assumption is broken, it will violate DustMite's guarantees and will corrupt the entire reduction.

If you are IO bounded, use `--temp-dir` with a RAM disk, or use symlinks.

**Comment by nordlow** [comment]
> > I believe that is an unfortunate assumption.
> 
> I doubt it, all breadth-first strategies are likely make some modifications to all inputs quickly.
> 
> > Could we have this behavior be controlled behind a flag?
> 
> No, I don't see the point. Furthermore, if the assumption is broken, it will violate DustMite's guarantees and will corrupt the entire reduction.
> 
> If you are IO bounded, use `--temp-dir` with a RAM disk, or use symlinks.

Ok, thanks for now. What about https://superuser.com/questions/1575147/filesystem-with-copy-on-write-hard-links/1575148#1575148?
