### ISSUE TITLE
Special case for import statements?

### ISSUE THREAD

**Issue by kinke** [CyberShadow/DustMite#78]
I've seen that dustmite likes to 'shorten' imports - e.g., `import std.algorithm` to `import std`. I guess that doesn't help compile times, especially for Phobos' `std`, so it might pay off to detect & handle imports differently.

**Comment by CyberShadow** [comment]
Yes, you can use the `--reject` switch to avoid this.

**Comment by CyberShadow** [comment]
As of d0af4a5111f69df1d0077a271314e0fc0b8c6f99, Dustmite should no longer reduce module names in import statements.
