### ISSUE TITLE
Add -man switch which opens the browser on the documentation for dustmite

### ISSUE THREAD

**Issue by WalterBright** [CyberShadow/DustMite#83]
Instead of just a url referring to the wiki.

The code to implement it is:

https://github.com/dlang/dmd/blob/master/compiler/src/dmd/root/man.d

**Comment by CyberShadow** [comment]
Best I can do is `--man`, due to `std.getopt` (and, well, the conventions it's implementing).

I actually wrote a proper man page for the sequel: https://cy.md/reduce/

I haven't worked on that in a while, though...

**Comment by WalterBright** [comment]
Sweet!
